name: apartment_managage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.2
  equatable: ^2.0.5

  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  logger: ^2.0.2+1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  timelines: ^0.1.0
  url_launcher: ^6.2.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/banner/
    - assets/icons/